development:
  author: Basil Konakov
socials:
  vk:
    alt: Rentabox | Wir im Netz | Rentabox-Seite im sozialen Netz &quot;Vkontakte&quot;
    title: Rentabox | Wir im Netz | Rentabox-Seite im sozialen Netz &quot;Vkontakte&quot;
  facebook:
    alt: Rentabox |Wir im Netz | Rentabox-Seite im sozialen Netz &quot;Facebook&quot;
    title: Rentabox | Wir im Netz | Rentabox-Seite im sozialen Netz &quot;Facebook&quot;
  instagram:
    alt: Rentabox | Wir im Netz | Rentabox-Seite im sozialen Netz &quot;Instagram&quot;
    title: Rentabox | Wir im Netz | Rentabox-Seite im sozialen Netz &quot;Instagram&quot;
